### ISSUE TITLE
more consistency

### ISSUE THREAD

**Issue by NekoFanatic** [nekos-best/nekos-best.py#3]
https://github.com/nekos-best/nekos-best.py/blob/044c23c21c36dbd54ae6a1f82c33164da7146636/nekosbest/models.py#L60
https://github.com/nekos-best/nekos-best.py/blob/044c23c21c36dbd54ae6a1f82c33164da7146636/nekosbest/models.py#L62

`URL` or `url`, both at the same time is inconsistent

**Comment by PredaaA** [comment]
Will be merged when #4 will be merged.
